/* eslint-disable no-unused-vars */
const crypto = require('crypto');
/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Course', [
      {
        id: crypto.randomUUID(),
        courseName: 'Acupuntura',
        courseStartDate: '2023-10-30',
        courseEndDate: '2023-11-13',
        description: 'La acupuntura es una antigua técnica de medicina oriental que utiliza agujas delgadas para aliviar el dolor y mejorar la salud. Descubre cómo funciona y sus beneficios en nuestro taller introductorio.',
        shortDescription: 'Aprende sobre la acupuntura, una práctica que utiliza agujas en puntos específicos del cuerpo para promover el bienestar. Nuestro taller te introduce a los conceptos básicos y cómo puede ayudarte.',
        amountclasses: 4,
        schedule: 'Lunes de 17:00 a 20:00',
        deleted: false,
        attendance: 0,
        visualized: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: crypto.randomUUID(),
        courseName: 'Acupuntura nivel 2',
        courseStartDate: '2023-10-30',
        courseEndDate: '2023-11-13',
        description: 'Si deseas profundizar en la acupuntura, nuestro taller de nivel 2 te ofrece técnicas avanzadas y conocimientos más especializados. Continúa tu viaje en el mundo de la acupuntura y amplía tus habilidades.',
        shortDescription: 'Para aquellos que desean ir más allá de lo básico, nuestro taller de acupuntura nivel 2 te llevará a un nivel más avanzado, explorando técnicas de tratamiento más detalladas y efectivas',
        amountclasses: 4,
        schedule: 'Lunes de 15:00 a 17:00',
        deleted: false,
        attendance: 0,
        visualized: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: crypto.randomUUID(),
        courseName: 'Semipermanente',
        courseStartDate: '2023-10-31',
        courseEndDate: '2023-11-14',
        description: 'El maquillaje semipermanente te permite lucir una apariencia impecable durante semanas. En este taller, aprenderás cómo aplicar y mantener el maquillaje semipermanente, realzando tu belleza de manera duradera.',
        shortDescription: 'Descubre el mundo del maquillaje semipermanente en nuestro taller. Aprenderás a resaltar tus rasgos faciales de manera que dure semanas, sin la necesidad de aplicar maquillaje diariamente.',
        amountclasses: 4,
        schedule: 'Martes de 17:00 a 20:00',
        deleted: false,
        attendance: 0,
        visualized: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: crypto.randomUUID(),
        courseName: 'Diseño y reciclaje: luminaria',
        courseStartDate: '2023-08-01',
        courseEndDate: '2023-10-01',
        description: 'Transforma objetos cotidianos en hermosas lámparas y luces decorativas en nuestro taller de diseño de luminarias. Aprende a reutilizar materiales de manera creativa y sostenible.',
        shortDescription: 'Da rienda suelta a tu creatividad y sostenibilidad en nuestro taller de diseño de luminarias. Aprende a crear iluminación única a partir de objetos reciclados y descubre cómo hacer tu hogar más hermoso y ecológico.',
        amountclasses: 4,
        schedule: 'Miércoles de 17:00 a 20:00',
        deleted: false,
        attendance: 0,
        visualized: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: crypto.randomUUID(),
        courseName: 'Diseño y reciclaje: packaging',
        courseStartDate: '2023-11-01',
        courseEndDate: '2023-12-06',
        description: 'En este taller, aprenderás a crear envases innovadores y respetuosos con el medio ambiente utilizando materiales reciclados. Desarrolla tus habilidades en diseño gráfico y packaging de manera sostenible.',
        shortDescription: 'Explora la combinación de diseño y sostenibilidad en nuestro taller de packaging. Descubre cómo transformar materiales reciclados en envases creativos y amigables con el planeta.',
        amountclasses: 4,
        schedule: 'Miércoles de 13:00 a 16:00',
        deleted: false,
        attendance: 0,
        visualized: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: crypto.randomUUID(),
        courseName: 'Diseño de imagen y video con Canva',
        courseStartDate: '2023-11-02',
        courseEndDate: '2023-12-07',
        description: 'Domina la creación de imágenes y videos atractivos con Canva en nuestro taller. Aprende a utilizar esta herramienta popular para dar vida a tus ideas visuales de manera sencilla y efectiva.',
        shortDescription: 'Explora el mundo del diseño de imágenes y videos con Canva en nuestro taller. Adquiere habilidades para crear contenido visual atractivo sin esfuerzo y lleva tus proyectos a otro nivel.',
        amountclasses: 4,
        schedule: 'Jueves de 16:00 a 20:00',
        deleted: false,
        attendance: 0,
        visualized: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Course', null, {});
  },
};
